# Generated by Django 3.1.4 on 2021-01-07 09:07

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('QuoraApp', '0005_auto_20210103_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=tinymce.models.HTMLField(verbose_name='Content'),
        ),
    ]
