# Generated by Django 3.1.4 on 2021-01-07 09:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('QuoraApp', '0006_auto_20210107_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=tinymce.models.HTMLField(),
        ),
    ]
