# Generated by Django 3.1.4 on 2021-01-09 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuoraApp', '0008_auto_20210108_1439'),
        ('QuoraApp', '0012_auto_20210108_1810'),
    ]

    operations = [
    ]
