# Generated by Django 3.1.4 on 2021-01-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuoraApp', '0013_merge_20210109_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
