# Generated by Django 3.1.4 on 2021-01-09 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuoraApp', '0014_auto_20210109_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='askedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='QuoraApp.member'),
        ),
    ]
