# Generated by Django 3.1.5 on 2021-01-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuoraApp', '0017_auto_20210111_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_pic',
            field=models.ImageField(blank=True, null=True, upload_to='tags/'),
        ),
    ]
