# Generated by Django 3.1.5 on 2021-01-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuoraApp', '0018_auto_20210119_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_pic',
            field=models.ImageField(blank=True, default='default_tag.png', null=True, upload_to='tags/'),
        ),
    ]
