# Generated by Django 3.1.5 on 2021-01-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuoraApp', '0020_auto_20210119_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, to='QuoraApp.Member'),
        ),
    ]
