# Generated by Django 3.1.5 on 2021-01-30 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuoraApp', '0021_member_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='followers',
            new_name='followings',
        ),
    ]
