# Generated by Django 3.1.5 on 2021-01-30 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuoraApp', '0022_auto_20210130_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='followings',
            new_name='followers',
        ),
    ]
